install:
  - sudo apt-get install build-essential cmake git libgtk2.0-dev pkg-config libavcodec-dev libavformat-dev libswscale-dev libgtest-dev
  - sudo ./install-deps.sh
  - sudo ldconfig

script:
  - make build
  - make test
