install:
  - sudo apt-get install build-essential cmake git libgtk2.0-dev libavcodec-dev libavformat-dev libswscale-dev
  - sudo ./install-deps.sh
  - sudo ldconfig

script:
  - ./test.sh
  - make

cache:
  directories: opencv-3.3.0-prebuilt
